-- INSERT INTO person(name,age,address) VALUES ('王云飞',32,'合肥');
-- INSERT INTO person(name,age,address) VALUES ('xx',31,'北京');
-- INSERT INTO person(name,age,address) VALUES ('zz',29,'南京');
-- INSERT INTO person(name,age,address) VALUES ('aa',28,'武汉');
-- INSERT INTO person(name,age,address) VALUES ('bb',27,'合肥');