INSERT INTO SYS_USER (username,password) VALUES ('wyf','wyf');
INSERT INTO SYS_USER (username,password) VALUES ('wisely','wisely');
INSERT INTO SYS_ROLE (name) VALUES ('ROLE_ADMIN');
INSERT INTO SYS_ROLE (name) VALUES ('ROLE_USER');
INSERT INTO SYS_USER_ROLES(SYS_USER_ID,ROLES_ID) VALUES (1,1);
INSERT INTO SYS_USER_ROLES(SYS_USER_ID,ROLES_ID) VALUES (2,2);